version: '3.0'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../:/app
    restart: always
    container_name: ${PROJECT_NAME}-php-fpm
    ports:
      - ${PROJECT_IP}:9100:9000
    depends_on:
      - postgres

  php-cli:
    build:
      context: ./php-cli
    volumes:
      - ../:/app
    command: sleep 10000
    container_name: ${PROJECT_NAME}-php-cli
    ports:
      - ${PROJECT_IP}:9200:9000

  postgres:
    build:
      context: ./postgres
    networks:
      - default
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    container_name: ${PROJECT_NAME}_db
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - ${PROJECT_IP}:9438:5432

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "${PROJECT_IP}:8085:80"
    depends_on:
      - php-fpm
